# Generated by Django 4.2.16 on 2024-10-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_alter_resume_email_weblink_skill_reference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='user',
            new_name='user_id',
        ),
    ]
