# Generated by Django 4.2.16 on 2024-10-29 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_rename_user_resume_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationhistory',
            options={'verbose_name_plural': 'Education History'},
        ),
        migrations.AlterModelOptions(
            name='employmenthistory',
            options={'verbose_name_plural': 'Employment History'},
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_template',
        ),
        migrations.AlterField(
            model_name='educationhistory',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_history', to='cv.resume'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='cv.resume'),
        ),
        migrations.DeleteModel(
            name='ResumeTemplate',
        ),
    ]
